# zmodload zsh/zprof # https://www.bigbinary.com/blog/zsh-profiling

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
#
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.zprezto/runcoms/path.zsh
source ~/.zprezto/runcoms/exports.zsh
source ~/.zprezto/runcoms/functions.zsh
source ~/.zprezto/runcoms/aliases.zsh
source ~/.zprezto/runcoms/external.zsh

# recompile_zcompdump()
autoload -Uz compinit
compinit -d "${ZDOTDIR:-$HOME}/.zcompdump"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# zprof # https://www.bigbinary.com/blog/zsh-profiling
