#!/usr/bin/env zsh
# Disable SC1091 for the entire script
# shellcheck disable=SC1091,SC2296
#
# zmodload zsh/zprof # https://www.bigbinary.com/blog/zsh-profiling

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export USER=${USER:l}
source "$HOME/.zprezto/runcoms/path.zsh"
source "$HOME/.zprezto/runcoms/exports.zsh"
source "$HOME/.zprezto/runcoms/functions.zsh"
source "$HOME/.zprezto/runcoms/external.zsh"
source "$HOME/.zprezto/runcoms/aliases.zsh"
source "$HOME/.zprezto/runcoms/keybindings.zsh"

# recompile_zcompdump()
autoload -Uz compinit
compinit -d "${ZDOTDIR:-$HOME}/.zcompdump"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"

# zprof # https://www.bigbinary.com/blog/zsh-profiling
